[package]
name = "lista3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.4"
nom = "7.1.3"
petgraph = "0.6.3"
pico-args = "0.5.0"
